version: "3"
services:

  scrapyd:
    image: snn2spade/myscrapyd-selenium
    ports:
      - "6800:6800"
    volumes:
      - ./data:/var/lib/scrapyd
      - /usr/local/lib/python3.5/dist-packages
    restart: always

  selenium:
    image: selenium/standalone-chrome:3.12.0-boron
    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm
    restart: always

  mongo:
    image: mongo:3.6-jessie
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:



